As dotnet tool
adliance/Togglr pull request #1
Opened 2020-09-25 19:55 UTC by kopfrechner

with options to generate a example config and use a custom confg to generate a report from toggl

2020-09-26 13:10 UTC, saxx requested changes

2020-09-26 13:10 UTC, saxx commented on Adliance.Togglr/Adliance.Togglr.csproj
> +    <Authors>Hannes Sachsenhofer</Authors>
I think "Christoph Kopf" is missing here now, too ;)

2020-09-26 13:10 UTC, saxx commented on Adliance.Togglr/TogglrConfigurationGeneratorParameters.cs
> +    [Verb("configuration-generator", HelpText = "Generate a template 'configuration.json' in the current folder")]
I think the verb should be an actual verb, like `generate-configuration`

2020-09-26 13:11 UTC, saxx commented
Thank you, great additions! Could you please also be so kind and update the readme to explain the new command line options?

2020-10-01 19:11 UTC, kopfrechner commented
Added requested changes :)

2020-10-02 18:56 UTC, saxx approved these changes

2020-10-02 18:56 UTC, merged